name: CICD for Backend

on:
  push:
    branches:
      - cicd-docker-ec2

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      
      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
      - name: Build Docker image
        run: docker build -t agure1996/tjf-b ./backend

      - name: Push Docker image to Docker Hub
        run: docker push agure1996/tjf-b:latest

  deploy:
    needs: build
    runs-on: self-hosted
    
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
      - name: Pull Docker image
        run: docker pull agure1996/tjf-b:latest
      
      - name: Deploy using Docker Compose
        run: |
          docker-compose down
          docker-compose up -d --remove-orphans backend
